### PR TITLE
Work around a bug in Sublime Text 3

### PR DESCRIPTION
**Pull request by rahul-ramadas**
See SublimeText/Issues#39. This fixes it.

### CODE REVIEW

**Comment by danielfrg** [comment]
Working great, thanks :)

**Comment by rahul-ramadas** [comment]
Do you know when this update will be available on Package Control? Do you have to do anything for that to happen?

**Comment by danielfrg** [comment]
I just tagged a new version, now we just need to wait for the package control crawler to grab it.

**Comment by danielfrg** [comment]
I just checked and the new version is on the package control site, you should be able to update now.

**Pull request merged**
