### PR TITLE
Refactor and new features

### PR DESCRIPTION
**Pull request by texastoland**
Easiest to pull down rather than make sense of the diff. Most significantly I added base classes (`FilesBase.py`) for building file sets and an API for using `Future`s (`Tools.py`) with ST callbacks. Additional details in the commit messages. Not necessarily ready for primetime until add/remove is implemented. Feedback welcome!

### CODE REVIEW

**Comment by texastoland** [comment]
I still have incoming changes. I meant to finish this weekend but got bogged down with a presentation. Add/remove bookmarks will be super straightforward now. Don't tag yet!

**Comment by danielfrg** [comment]
Its ok, just wanted to try the changes. I got an Exception so i reverted the merge.

```
File "/Users/danielfrg/Library/Application Support/Sublime Text 3/Packages/Open/Open.py", line 17, in run
    self.bind_settings(
AttributeError: 'OpenBrowseCommand' object has no attribute 'bind_settings'
```

**Comment by texastoland** [comment]
Strange it should have that method by extending `SettingsProxy`. Did it apply cleanly?

**Comment by texastoland** [comment]
The only local changes I haven't committed are to revert `TRANSIENT` (it sucked as a feature) and tackle an issue with symlinks.

**Comment by texastoland** [comment]
You can also just switch to my branch when you want to try anything.

**Comment by danielfrg** [comment]
Actually nevermind, i think i didn't restart sublime and it got confused. Now its working fine.

**Comment by danielfrg** [comment]
Yes, i confirmed this, everything is working fine now. But i probably made a git mess with the reverts so you probably want to rebase.

**Comment by texastoland** [comment]
No worries I usually rebase. Interested what you think. I originally appreciated the simplicity of your plugin. The only reason I implemented `Future` is because I couldn't import the standard ones. And `FileList` provided a convenient ADT-like abstraction. I'm trying to keep every method under about five lines. I find more usually indicates I'm missing something. E.g. right now adding a folder to the side bar isn't as clean as I'd like. Abstracting it will help writing bookmarks to settings too.

**Comment by danielfrg** [comment]
Yes, I was looking at the code and I believe that now its complex and I am not sure what that complexity gives us. Before merging this every file and function made sense, now I am not sure.

What i like are the simple features you added like showing the directories names on `.` and `..`, the `persistent_browsing` and the `exclude_patterns` but about the Futures i dont see the value on adding the code if the plugin was working fine.

**Comment by texastoland** [comment]
The motivation was two-fold:
1. The API was very stateful. That's ST's fault not yours. But you had to save various state in instance variables and hope (which was guaranteed) callbacks happened before state changed again. I also didn't expect to have to implement it myself since it's standard in Python 3.
2. That API also forced you to associate data between lists. That association made it awkward to isolate path (normalized) from what rendered (usually base name) from what originally got passed in (which is how `.` gets special treatment) and do manipulations like filter and sort while maintaining indices.

I could see a case for stripping `Future` though. I didn't expect to have to implement it myself since it's standard in Python 3.

**Comment by danielfrg** [comment]
Yeah, those were some issues I had that I fix with those "synced" lists, i didn't like it but since it worked for a small project it was fine by me.

I am thinking maybe we just need the right abstraction for that. I don't think ST is using python 3.4 so maybe we should wait for an update on their side to make this type of changes. The bad part is that sublime development its not going exactly fast those days.

For now I am going to revert this again. That was definitely my bad because I got lazy and merge it instead of pulling the PR locally.

**Comment by texastoland** [comment]
I would just rebase the merge back out. `Future` only handles state. `FileList` cool?

**Comment by danielfrg** [comment]
Yes, FilesList makes sense to me.

**Comment by texastoland** [comment]
Rad I'll nix it. I'll also nix `preview_on_click`. It wasn't helpful. PR after add/remove.

**Pull request merged**
